name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cd to Lean4 directory
        run: cd proofs
      - uses: leanprover/lean-action@v1
      - name: Build Lean files there
        run: lean --make
